<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.
// genesis();

get_header(); 
get_template_part( 'page-templates/theme-sections/follow-sidebar', 'section' ); 
?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
 var js, fjs = d.getElementsByTagName(s)[0];
 if (d.getElementById(id)) return;
 js = d.createElement(s); js.id = id;
 js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<?php echo FB_APP_ID; ?>";
 fjs.parentNode.insertBefore(js, fjs); }
(document, 'script', 'facebook-jssdk'));
</script>

<div class="single-post pt-25">
	<div class="header_image position-relative">
		<div class="header">
			<div class="container">
				<div class="breadcrumbs-wrapper position-relative">
      				<div class="breadcrumbs-inside">
      					<?php echo yoast_breadcrumb(); ?>
  					</div>
  				</div>
			</div>
		</div>
	</div>

	<div class="single_post_page">
		<div class="container">
			<div class="row">
				<?php if ( have_posts() ) : ?>
					<?php			
					while ( have_posts() ) :
					  	the_post();
					 	update_post_meta($post->ID, 'hk_views', get_post_meta($post->ID, 'hk_views', true) + 1);
						$before_image_id = get_post_meta(get_the_id(), 'hk_image_before_diet_id', true);
						$before_image_url = wp_get_attachment_image_src($before_image_id, 'medium')[0];
						$after_image_id = get_post_meta(get_the_id(), 'hk_image_after_diet_id', true);
						$after_image_url = wp_get_attachment_image_src($after_image_id, 'medium')[0];

						$before_weight = get_post_meta(get_the_id(), 'hk_weight_before_diet', true);
						$after_weight = get_post_meta(get_the_id(), 'hk_weight_after_diet', true);
						$before_age = get_post_meta(get_the_id(), 'hk_age_before_diet', true);
						$after_age = get_post_meta(get_the_id(), 'hk_age_after_diet', true);
						$before_fat = get_post_meta(get_the_id(), 'hk_body_fat_before_diet', true);
						$after_fat = get_post_meta(get_the_id(), 'hk_body_fat_after_diet', true);
					?>
						<header class="entry-header col-12">
							<span>
								<span class="category">
									<a target="_blank" title="Transformation" href="<?php echo get_post_type_archive_link(get_post_type()); ?>" rel="category tag">Transformation</a>
								</span>
								<span class="dot"><i class="fa fa-circle" aria-hidden="true"></i></span>
								<span class="last-read"><?php echo get_mins_read(); ?> MIN READ</span>
								<span class="dot"><i class="fa fa-circle" aria-hidden="true"></i></span>
								<?php $post_date = get_the_date( 'M j, Y' ); ?>
								<span class="last-read"><?php echo $post_date; ?></span>
							</span>
						</header>

						<div class="post-title col-12">
							<h1 class="entry-title pb-3"><?php the_title(); ?></h1>
						</div>
						<div class="col-md-8 col-12 transformation-template-section">
							<div class="transformation-section-single-image mb-2">
								<div class="blog_featured_img my-4 content-mobile">
									<a class="row" href="<?php the_permalink(); ?>" title="<?php the_title(); ?>">
									<div class="position-relative col-md-6 pl-3 pr-1 transform">
										<img src="<?php echo $before_image_url; ?>" alt="<?php the_title(); ?>" title="<?php the_title(); ?>" />
										<div class="img-tag px-3 py-1">Before</div>
									</div>
									<div class="position-relative col-md-6 pl-1 pr-3 transform">
										<img src="<?php echo $after_image_url; ?>" alt="<?php the_title(); ?>" title="<?php the_title(); ?>" />
										<div class="img-tag px-3 py-1">After</div>
									</div>
									</a>
								</div>
								<div class="content-fields p-3">
									<div class="content-fields-titles row">
										<label class="content-fields-titles-single col-md-2 pr-2">Age</label>
										<label class="content-fields-titles-single col-md-3 px-2">Then</label>
										<label class="content-fields-titles-single col-md-2 px-2 transformation-border-right">Now</label>
										<label class="content-fields-titles-single col-md-3 px-2">Bodyfat then</label>
										<label class="content-fields-titles-single col-md-2 px-2">Now</label>
									</div>
									<div class="content-fields-values row">
										<span class="content-fields-values-single col-md-2 pr-2"><?php echo $before_age.'/'.$after_age; ?></span>
										<span class="content-fields-value-single transformation-before col-md-2 px-2"><?php echo $before_weight; ?>kg</span>
										<span class="content-fields-value-single transformation-seperator col-md-1 px-2">></span>
										<span class="content-fields-values-single transformation-after transformation-border-right col-md-2 px-2"><?php echo $after_weight; ?>kg</span>
										<span class="content-fields-values-single transformation-before col-md-2 px-2"><?php echo is_numeric($before_fat) ? $before_fat.'%' : $before_fat; ?></span>
										<span class="content-fields-values-single transformation-seperator col-md-1 px-2">></span>
										<span class="content-fields-values-single transformation-after col-md-2 px-2"><?php echo is_numeric($after_fat) ? $after_fat.'%' : $after_fat; ?></span>
									</div>
								</div>
								<div class="blog_featured_img my-4 content-desktop">
									<a class="row" href="<?php the_permalink(); ?>" title="<?php the_title(); ?>">
									<div class="position-relative col-md-6 pl-3 pr-1 transform">
										<img src="<?php echo $before_image_url; ?>" alt="<?php the_title(); ?>" title="<?php the_title(); ?>" />
										<div class="img-tag px-3 py-1">Before</div>
									</div>
									<div class="position-relative col-md-6 pl-1 pr-3 transform">
										<img src="<?php echo $after_image_url; ?>" alt="<?php the_title(); ?>" title="<?php the_title(); ?>" />
										<div class="img-tag px-3 py-1">After</div>
									</div>
									</a>
								</div>
							</div>
							<?php
								$description = get_post_meta($post->ID, 'hk_description', true);
								if ($description) :
								?><div class="entry-description"><?php echo $description; ?></div><?php 
								endif;
							?>
							<div class="entry-content">
								<div class="my-2">
									<?php the_content(); ?>
								</div>
								<?php $transform_reason = get_post_meta($post->ID, 'hk_transform_reason', true); 
									if($transform_reason): ?>
									<div class="my-2">
											<h2 class="entry-content-heading">Why you decided to Transform?</h2>
											<div class="entry-content-single"><?php echo $transform_reason; ?></div>
									</div>
								<?php endif; ?>
								<?php $accomplish_goal = get_post_meta($post->ID, 'hk_accomplish_goal', true); 
									if($accomplish_goal): ?>
									<div class="my-2">
											<h2 class="entry-content-heading">How did you accomplish your Goal:</h2>
											<div class="entry-content-single"><?php echo $accomplish_goal; ?></div>
									</div>
								<?php endif; ?>
								<?php $training_routine = get_post_meta($post->ID, 'hk_training_routine', true); 
									if($training_routine): ?>
									<div class="my-2">
											<h2 class="entry-content-heading">Training routine that helped you achieve your Goals</h2>
											<div class="entry-content-single"><?php echo $training_routine; ?></div>
									</div>
								<?php endif; ?>
								<?php $supplements_that_helped = get_post_meta($post->ID, 'hk_supplements_that_helped', true); 
									if($supplements_that_helped): ?>
									<div class="my-2">
											<h2 class="entry-content-heading">Supplements:</h2>
											<div class="entry-content-single"><?php echo $supplements_that_helped; ?></div>
									</div>
								<?php endif; ?>
								<?php $challenges = get_post_meta($post->ID, 'hk_challenges', true); 
									if($challenges): ?>
									<div class="my-2">
											<h2 class="entry-content-heading">What challenges did you face?</h2>
											<div class="entry-content-single"><?php echo $challenges; ?></div>
									</div>
								<?php endif; ?>
								<?php $how_did_you_overcome = get_post_meta($post->ID, 'hk_how_did_you_overcome', true); 
									if($how_did_you_overcome): ?>
									<div class="my-2">
											<h2 class="entry-content-heading">How did you overcome these challenges?</h2>
											<div class="entry-content-single"><?php echo $how_did_you_overcome; ?></div>
									</div>
								<?php endif; ?>
								<?php $future_suggestion = get_post_meta($post->ID, 'hk_future_suggestion', true); 
									if($future_suggestion): ?>
									<div class="my-2">
											<h2 class="entry-content-heading">Suggestion for future transformers</h2>
											<div class="entry-content-single"><?php echo $future_suggestion; ?></div>
									</div>
								<?php endif; ?>
							</div>  
							<!-- <div class="transformation-story">
								<h4 class="transformation-story_heading">Submit your transformation story and motivate other people to change their life.</h4>
								<a type="submit" class="btn hk-btn">Submit Now</a>
							</div> -->
							  <?php 
                                $postUrl = 'http' . ( isset( $_SERVER['HTTPS'] ) ? 's' : '' ) . '://' . "{$_SERVER['HTTP_HOST']}{$_SERVER['REQUEST_URI']}"; 
                                $title = urlencode(html_entity_decode(get_the_title(), ENT_COMPAT, 'UTF-8'));
                            ?>
							<div class="share share-desktop">
								<div class="share-title section-title"> Share </div>
								<div class="share-icons">
									<a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $postUrl; ?>" class="text-orange f-28" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
									<a href="https://twitter.com/intent/tweet?text=<?php echo $title; ?>&amp;url=<?php echo $postUrl; ?>" class="text-orange f-28" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
								</div>
							</div>
							<div class="share share-mob">
								<div class="share-title section-title"> Share Article </div>
								<div class="share-icons">
									<a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $postUrl; ?>" class="text-orange f-28" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
									<a href="https://twitter.com/intent/tweet?text=<?php echo $title; ?>&amp;url=<?php echo $postUrl; ?>&amp;via=WPCrumbs" class="text-orange f-28" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
								</div>
							</div>
							<div class="comment-block">
								<?php if(isset($_GET['unapproved']) && $_GET['unapproved']): ?>
								<div class="alert alert-success">
								  <strong>Success!</strong> Your comment has been sent for moderation.
								</div>
							<?php endif;
								$fields =  array(
								    'author' =>
								        '<input class="comment-input comment-input-name" required name="author" type="text" value="' . esc_attr( $commenter['comment_author'] ) .'" size="30" placeholder="'.__('Name','text-domain').( $req ? ' (Required)' : '' ).'"/>',
								    'email' =>
								        '<input required class="comment-input comment-input-email" name="email" type="text" value="' . esc_attr(  $commenter['comment_author_email'] ) .'" size="30" placeholder="'.__('Email','text-domain').( $req ? ' (Required)' : '' ).'"/>',
								);
								$args = array(
								    'id_form'           => 'commentform',
								    'class_form'        => 'comment-form',
								    'id_submit'         => 'submit',
								    'class_submit'      => 'submit',
								    'name_submit'       => 'submit',
								    'submit_button'     => '<input name="%1$s" type="submit" id="%2$s" class="%3$s" value="%4$s" />',
								    'title_reply'       => '',
								    'title_reply_to'    => __( 'Reply to %s','text-domain' ),
								    'cancel_reply_link' => __( 'Cancel comment','text-domain' ),
								    'label_submit'      => __( 'Post comment','text-domain' ),
								    'format'            => 'xhtml',
								    'comment_field'     =>  '<textarea id="comment" name="comment" placeholder="'.__('Add a comment...','text-domain').'" cols="45" rows="2" aria-required="true">' .'</textarea>',
								    'logged_in_as'      => '',
								    'comment_notes_before' => '',
								    'fields'            => $fields,
								);

								comment_form( $args );
								$comments = get_comments( array('status' => 'approve','order' => 'DESC', 'post_id' => $post->ID) );
								?>

								<ul class="comments-list">
								<?php foreach ($comments as $comment): ?>
									<li>
										<div class="my-4">
											<div class="comment-author-image">
												<img src="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/avatar.jpg" alt="search" class="search-icon-white">
											</div>
											<div class="comment-text">
												<div class="comment-text-author"><?php echo $comment->comment_author; ?></div>
												<div class="comment-text-content"><?php echo $comment->comment_content; ?></div>
												<div class="comment-text-date"><?php display_human_readable_time($comment->comment_date); ?></div>
											</div>
										</div>
									</li>
								<?php endforeach; ?>
								</ul>
							</div>
							<div class="latest-reads">
								<?php echo do_shortcode('[read-these-next-transformations]'); ?>
							</div>
						</div>
					<?php endwhile; ?>
				<?php endif; ?>
				<div class="col-md-4 col-12">
					<?php
	                    get_sidebar();
	                ?>
				</div>
			</div>
			<!-- <div class="fb-comments" data-href="<?php the_permalink() ?>"></div> -->
		</div>
	</div>
</div>

<?php
get_footer();

?>
