<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.
// genesis();

get_header(); 
get_template_part( 'page-templates/theme-sections/follow-sidebar', 'section' ); 
?>
<div id="fb-root"></div>
<!-- <script>(function(d, s, id) {
 var js, fjs = d.getElementsByTagName(s)[0];
 if (d.getElementById(id)) return;
 js = d.createElement(s); js.id = id;
 js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<?php /* echo FB_APP_ID; */ ?>";
 fjs.parentNode.insertBefore(js, fjs); }
(document, 'script', 'facebook-jssdk'));
</script> -->

<div class="single-post pt-25">
	<div class="header_image position-relative">
		<div class="header">
			<div class="container">
				<div class="breadcrumbs-wrapper position-relative">
      				<div class="breadcrumbs-inside">
      					<?php echo yoast_breadcrumb(); ?>
  					</div>
  				</div>
			</div>
		</div>
	</div>

	<div class="single_post_page">
		<div>
			<div>
				<?php if ( have_posts() ) : ?>
					<?php while ( have_posts() ) :
					  		the_post();
					  		update_post_meta($post->ID, 'hk_views', get_post_meta($post->ID, 'hk_views', true) + 1); ?>
						<header class="entry-header">
							<?php 
								$featured_video = get_field('featured_video_link');
								if ($featured_video){ ?>
									<div class="blog_featured_video">
										<div class="embed-container">
											<?php echo $featured_video; ?>
										</div>
									</div>
								<?php } ?>
							<div class="smaller-container container post-title">
								<h1 class="entry-title"><?php the_title(); ?></h1>
							</div>
							<div class="smaller-container container">
								<?php get_template_part( 'page-templates/theme-sections/author-bar-top', 'section' ); ?>
							</div>
						</header>
						<div class="smaller-container container single-post-content">
							<div class="entry-content"><?php the_content(); ?></div>
							<?php 
								$postUrl = 'http' . ( isset( $_SERVER['HTTPS'] ) ? 's' : '' ) . '://' . "{$_SERVER['HTTP_HOST']}{$_SERVER['REQUEST_URI']}"; 
								$title = urlencode(html_entity_decode(get_the_title(), ENT_COMPAT, 'UTF-8'));
							?>
							<div class="share share-desktop">
								<div class="share-icons">
									<a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $postUrl; ?>" class="share-icons__icon" target="_blank"><i class="fa fa-facebook-square" aria-hidden="true"></i>Share on Facebook</a>
									<a href="https://twitter.com/intent/tweet?text=<?php echo $title; ?>&amp;url=<?php echo $postUrl; ?>&amp;via=Healthkart" class="share-icons__icon" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i>Share on Twitter</a>
									<!-- linkedin -->
									<a href="https://www.linkedin.com/shareArticle?mini=true&amp;url=<?php echo $postUrl; ?>&amp;title=<?php echo $title; ?>&amp;source=healthkart.com/connect/" class="share-icons__icon" target="_blank"><i class="fa fa-linkedin-square" aria-hidden="true"></i>Share on LinkedIn</a>
									<!-- Whatsapp sharing onn desktop -->
									<!-- <a href="https://web.whatsapp.com/send?text=<?php /* echo $postUrl; */ ?>" id="whatsapp-desktop" class="whatsapp social boxed-icon white-fill" data-href="<?php /* echo $postUrl; */ ?>" data-action="share/whatsapp/share"><i class="fa fa-whatsapp"></i></a> -->
								</div>
							</div>
							<div class="share share-mob">
								<div class="share-icons">
									<a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $postUrl; ?>" class="share-icons__icon" target="_blank"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
									<a href="https://twitter.com/intent/tweet?text=<?php echo $title; ?>&amp;url=<?php echo $postUrl; ?>&amp;via=Healthkart" class="share-icons__icon" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
									<a href="https://www.linkedin.com/shareArticle?mini=true&amp;url=<?php echo $postUrl; ?>&amp;title=<?php echo $title; ?>&amp;source=healthkart.com/connect/" class="share-icons__icon" target="_blank"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
									<!-- Whatsapp sharing onn mobile -->
									<!-- <a href="whatsapp://send?text=<?php /* echo $postUrl; */ ?>" id="whatsapp-mobile" class="whatsapp social boxed-icon white-fill" data-href="<?php /* echo $postUrl; */ ?>" data-action="share/whatsapp/share"><i class="fa fa-whatsapp"></i></a> -->
								</div>
							</div>
							<?php
								$tag_list = $tags = get_the_term_list( $post->ID, 'video_tag', '',' ',''); 
								if ($tags){ ?>
									<div class="article-tags">
										<span class="article-tags__heading">Tags:</span>
										<?php print_r ($tags);?>
									</div>
								<?php } ?>
						</div>
						<div class="smaller-container container">
							<?php get_template_part( 'page-templates/theme-sections/author-bar-bottom', 'section' ); ?>
						</div>
						<div class="divider-eyes">
							<img src="<?php echo get_stylesheet_directory_uri(); ?>/assets/images/eyes.svg" alt="divider">
						</div>
						<div class="container m-auto latest-reads">
							<?php echo do_shortcode('[read-these-next]'); ?>
						</div>
					<?php endwhile; ?>
				<?php endif; ?>
				<div class="container subscribe-container">
					<?php echo do_shortcode('[Subscribe-form]'); ?>
				</div>
			</div>
			<!-- <div class="fb-comments" data-href="<?php /* the_permalink() */ ?>"></div> -->
		</div>
	</div>
</div>

<?php
get_footer();

?>
